# Generated by Django 6.0.2 on 2026-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True),
        ),
    ]
