# Generated by Django 6.0.2 on 2026-04-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='owner',
        ),
    ]
