# Generated by Django 6.0.2 on 2026-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
