# Generated by Django 6.0.2 on 2026-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_alter_mpesatransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='receipt_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
