# Generated by Django 6.0.2 on 2026-03-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_alter_mpesatransaction_options_and_more'),
        ('properties', '0002_remove_tenant_payment_identifier_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', unique=True),
        ),
    ]
