# Generated by Django 6.0.2 on 2026-04-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_invoice_number'),
        ('mpesa', '0004_alter_mpesatransaction_property'),
        ('properties', '0002_remove_tenant_payment_identifier_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='properties.tenant'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='properties.unit'),
        ),
    ]
