# Generated by Django 6.0.2 on 2026-03-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='payment_identifier',
        ),
        migrations.AddField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='unique_active_lease_per_unit'),
        ),
    ]
