# Generated by Django 6.0.2 on 2026-04-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_tenant_payment_identifier_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='due_day',
            field=models.IntegerField(default=5),
        ),
    ]
