# Generated by Django 6.0.2 on 2026-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_lease_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lease',
            name='opening_arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
